permalink: pretty
plugins:
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-feed
  - jekyll-remote-theme
  - jeql
# remote_theme: "yous/whiteglass"
remote_theme: "fongandrew/hydeout"
title: "Florian Thomas"
description: "my personal blog"
twitter:
  username: "Crunch09"
jeql:
  github:
    url: "https://api.github.com/graphql"
